service: jasonhou

package:
  individually: true
  exclude:
    - node_modules/**
    - venv/**

configValidationMode: error

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1

resources:
  # lambda resources
  - ${file(./aws-resources/lambdas/handleNowPlaying.yml):supportingResources}

functions:
  # lambda resources
  - handleNowPlaying: ${file(./aws-resources/lambdas/handleNowPlaying.yml):handleNowPlaying}
